### PR TITLE
add os specific in launch.json

### PR DESCRIPTION
**Pull request by Huibean**
remove hardcode os setting from setting.json, same changes as bootloader project

### CODE REVIEW

**Comment by tridge** [comment]
i'd really like to automate this, probably with a modified makefile-tools for AM32

**Comment by Huibean** [comment]
> i'd really like to automate this, probably with a modified makefile-tools for AM32

before that, this could be a buffer stage, with this merge could save a lot time on rebasing and unstage

**Comment by Huibean** [comment]
add a windows auto setup cmd file

**Review by tridge — APPROVED** [review]
thanks!

**Comment by Huibean** [comment]
add script for debian linux and macos

**Review by AlkaMotors — APPROVED** [review]

**Pull request merged**
