### PR TITLE
Added DroneCAN support

### PR DESCRIPTION
**Pull request by tridge**
This adds DroneCAN support to AM32 and enables it on the VIMDRONES_L431 ESC
image

Features working:
 - [x] motors spinning
 - [x] parameter save/load/erase
 - [x] debug text messages
 - [x] ESC status messages working
 - [x] firmware update over DroneCAN
 - [x] ArmingStatus working
 - [x] node restart
 - [x] bi-directional support
 - [x] firmware signature checking in CAN bootloader: https://github.com/am32-firmware/AM32-bootloader/pull/21
 - [x] need to switch L431 to using HSE crystal instead of HSI

Remaining issues:
 - [ ] cell count should be a separate parameter, detection can be unreliable

### CODE REVIEW

**Comment by MallikarjunSE** [comment]
Hey @tridge this is directly running DroneCAN on MCU used to control ESCs? 
I'm currently designing 4in1 ESC with STSPIN32F0. I'd be happy to shift to L431 or G431 if it's DroneCAN support directly.

**Comment by ianrmurphy** [comment]
@tridge now we have a bootloader for the B-G431B-ESC1, it should be possible to rebase this support onto that ESC. Can you review that task? If not I will be able to take a look later in the week. Note, I would need to setup a DroneCAN environment first.I have a suitable FC and I think I have an SLCAN device somewhere, need to dig it out and give it a try.
Otherwise, is there a DBC file available for DroneCAN? If so I have other CAN tools ready to go.

**Comment by ianrmurphy** [comment]
Also, I have tonight run a motor using the ST MC Workbench FOC code, not AM32. Would be possible I think to extend that for DroneCAN support without much work.

**Comment by Huibean** [comment]
2024.10.16 fligth test update
logs - https://drive.google.com/file/d/15NNZuhAJ8YnBaFrGB5Z9oo6JF-dytK4L/view?usp=sharing

main firmware last commit
```
commit 97b97f4aff9d7d9e94e3f6427936a9ecf0a265d7 (HEAD -> pr-DroneCAN-support, tridge/pr-DroneCAN-support)
Author: Andrew Tridgell <andrew@tridgell.net>
Date:   Wed Oct 16 09:30:43 2024 +1100

    DroneCAN: fill in defaults and min/max
```
bootloader last commit
```
commit b1f1337c298784f05585f06e643c6feaba929aa8 (HEAD -> pr-can-bootloader, tridge/pr-can-bootloader)
Author: Andrew Tridgell <andrew@tridgell.net>
Date:   Wed Oct 9 17:14:49 2024 +1100

    DroneCAN: display human readable boot reason
```
Main Target
VIMDRONES_NANO_L431_CAN
Bootloader Target
AM32_L431_BOOTLOADER_PA2_CAN
Setup
ESC: Vimdrones ESC NANO CAN
FC: Holybro Pix32V5
Frame: S500
Motor: 2216-960kv kit motor
Props: 10 inch kit prop
7711729069729_ pic_hd

**Pull request merged**
