### PR TITLE
Add EXUAV 70A ESC support

### PR DESCRIPTION
**Pull request by robustini**
EXUAV 70A ESC is quite similar to NeutronRC with F051, bootloader PB4.
Current ratio calibrated with a current clamp to a stable value of 10A.

immagine

immagine

### CODE REVIEW

**Comment by freasy** [comment]
Have you measured deadtiming with a scope? If yes, please share the scope images.

**Comment by robustini** [comment]
> Have you measured deadtiming with a scope? If yes, please share the scope images.

No i'm sorry, being basically the NeutronRC I kept its settings, only calibrated voltage and current ratio.

**Comment by robustini** [comment]
Comparison in real flight between current and voltage measured by FC and ESC.
Pretty much in line, considering that the sensors on the FC are definitely not too reliable.

immagine

immagine

**Review by freasy — APPROVED** [review]

**Comment by robustini** [comment]
Unfortunately, this hardware does not natively provide the capacitor on the RC filter to the PA pin of the MCU, and this produces a lot of noise in the sensed current.

immagine

I then added a 100 nF capacitor where it actually would like.

immagine

And here is the stability of the current after the hardware modification.

immagine

In BLHeli32 probably the filtering was done via firmware, with AM32 if you want a low-noise current reading this modification on this ESC is necessary, as are you many others based on F051.

**Comment by robustini** [comment]
The datasheet also shows that the capacitor is needed.

Senza titolo

**Comment by robustini** [comment]
I am closing because @AlkaMotors will integrate it in the V3 version, it is already in the experimental code.

**Pull request closed without merging**
