### PR TITLE
add l431 target support

### PR DESCRIPTION
**Pull request by Huibean**

### CODE REVIEW

**Comment by AlkaMotors** [comment]
L431 support has already been added just merged to main yet. 
https://github.com/am32-firmware/AM32/tree/Kiss_Ardupilot_DshotBranch

**Comment by Huibean** [comment]
> L431 support has already been added just not merged to main yet. https://github.com/am32-firmware/AM32/tree/Kiss_Ardupilot_DshotBranch

that is keil build support right? my PR is base on makefile, it will be helpful for continue the makefile workflow improve

**Comment by AlkaMotors** [comment]
Unless you can show me how to build and debug , view live variable and registers as easily as Keil and for a new user to get set up to build then we will be sticking with the Keil build. If you can do a video or tutorial or something to show the process of setting up the dev environment . Building and uploading the firmware and then viewing registers and variables in operation then that would be a big help. With keil you download the ide, install the mcu pack. Open the project file.

**Comment by Huibean** [comment]
That’s a good idea, I can do it

AlkaMotors ***@***.***>于2024年7月18日 周四19:34写道：

**Comment by Huibean** [comment]
> Unless you can show me how to build and debug , view live variable and registers as easily as Keil and for a new user to get set up to build then we will be sticking with the Keil build. If you can do a video or tutorial or something to show the process of setting up the dev environment . Building and uploading the firmware and then viewing registers and variables in operation then that would be a big help. With keil you download the ide, install the mcu pack. Open the project file.

That’s a good idea, I can do it

**Comment by Huibean** [comment]
share @tridge 's tutorial video https://www.youtube.com/watch?v=2hQvTfp1R7k

**Comment by Huibean** [comment]
new start base on Kiss_Ardupilot_DshotBranch

**Pull request closed without merging**
