### PR TITLE
remove make stuff

### PR DESCRIPTION
**Pull request by freasy**

### CODE REVIEW

**Comment by tridge** [comment]
I'd prefer to fix the Makefile system instead of removing it

**Comment by freasy** [comment]
> I'd prefer to fix the Makefile system instead of removing it

Make is not the issue, the GCC arm toolchain needs to get fixed

**Comment by tridge** [comment]
@freasy here is an alternative that fixes up the gcc build and adds a CI job to test it:
https://github.com/am32-firmware/AM32/pull/34

**Comment by tridge** [comment]
@freasy could be closed now?

**Pull request closed without merging**
