### PR TITLE
vscode build support

### PR DESCRIPTION
**Pull request by tridge**
This adds vscode build support on linux and windows. It supports building and debugging AM32 using vscode on both windows and linux. It also supports command line builds on linux.

For windows you will need these tools:
http://uav.tridgell.net/AM32/tools/windows-tools.zip
on linux you need these:
http://uav.tridgell.net/AM32/tools/linux-tools.zip

You will need to install vscode, along with the following extensions:
 - C/C++
 - Coxtex-Debug
 - Makefile Tools

quick demos:
https://youtu.be/2hQvTfp1R7k?si=sn1L5J9G7VJJssKF
https://www.youtube.com/watch?v=CSHP63D_ojw

this PR builds on top of #34

### CODE REVIEW

**Comment by ianrmurphy** [comment]
Commit d3445bca97c183ef67a4e73a3bb748c4c8599183 has broken the Keil IDE builds. They don't use the makefile. However, they are ahead of the makefile builds in terms of target support, so I think this would need to be fixed as they are clearly being used by some contributors.

**Comment by ianrmurphy** [comment]
> Commit [d3445bc](https://github.com/am32-firmware/AM32/commit/d3445bca97c183ef67a4e73a3bb748c4c8599183) has broken the Keil IDE builds. They don't use the makefile. However, they are ahead of the makefile builds in terms of target support, so I think this would need to be fixed as they are clearly being used by some contributors.

https://github.com/am32-firmware/AM32/pull/37#issuecomment-2236277866

**Comment by tridge** [comment]
@ianrmurphy fixed in #44 - @AlkaMotors asked me to rebase on his current dev branch, so I did that in a new PR, and fixed the keil build there

**Comment by tridge** [comment]
this PR is replaced by #44

**Pull request closed without merging**
