### PR TITLE
change license to MIT

### PR DESCRIPTION
**Pull request by freasy**
i approve this

@AlkaMotors and @frank26080115  please approve

### CODE REVIEW

**Comment by howels** [comment]
Be aware that the MIT license would allow someone to fork the code, rename it and sell it without contributing back to the project.

https://fossa.com/blog/open-source-licenses-101-mit-license/

**Comment by tridge** [comment]
if the project wants to flourish and not end up as lots of non-contributing forks then staying with the GPL is the best option

**Comment by Quick-Flash** [comment]
> if the project wants to flourish and not end up as lots of non-contributing forks then staying with the GPL is the best option

Well, this really depends, many projects have benefitted from not selecting GPL licenses. There are benefits and downsides to both licenses, but I do have doubts that there would be mire non-contributing forks than with a GPL license. Take a look at most projects and likely less than 10% or forks actually contribute back to the main project. Only difference is if you happen to find a fork with changes you could grab it yourself, but even this is not a very common practice in open source projects.

**Comment by howels** [comment]
> > if the project wants to flourish and not end up as lots of non-contributing forks then staying with the GPL is the best option
> 
> Well, this really depends, many projects have benefitted from not selecting GPL licenses. There are benefits and downsides to both licenses, but I do have doubts that there would be mire non-contributing forks than with a GPL license. Take a look at most projects and likely less than 10% or forks actually contribute back to the main project. Only difference is if you happen to find a fork with changes you could grab it yourself, but even this is not a very common practice in open source projects.

MIT Vs GPL are really separated by the ability to take the code, rename it and sell it without sharing the source. Board cloners would love a MIT license as they could relabel and sell the code with no legal recourse.

**Pull request closed without merging**
